### ISSUE TITLE
Does this project can be trained with torch.nn.DataParallel ?

### ISSUE THREAD

**Issue by icepeak2015** [foamliu/Speech-Transformer#5]
I want to train Speech-Transformer with multi GPU, so i change some code of the train.py, like 
`model = model.cuda(device=devices[0])`
`model = nn.DataParallel(model, device_ids=devices)`
and also change the variabls like
`padded_input = padded_input.cuda(device=devices[0])`
`padded_target = padded_target.cuda(device=devices[0])`
`input_lengths = input_lengths.cuda(device=devices[0])`
the devices is GPU list, like device=[0,1] defined in config.py
 after these changes , i run the train.py got the following errors:
RuntimeError: Gather got an input of invalid size: got [16, 16, 4335], but expected [16, 25, 4335] (gather at /pytorch/torch/csrc/cuda/comm.cpp:226)
This project can be trained in one GPU, can't this project be trained in multi GPU ?

**Comment by deep-darkfantasy** [comment]
hello，Have you encountered this problem
Traceback (most recent call last):
File "G:/github/Speech-Transformer-master/Speech-Transformer-master/train.py", line 170, in
main()
File "G:/github/Speech-Transformer-master/Speech-Transformer-master/train.py", line 166, in main
train_net(args)
File "G:/github/Speech-Transformer-master/Speech-Transformer-master/train.py", line 73, in train_net
logger=logger)
File "G:/github/Speech-Transformer-master/Speech-Transformer-master/train.py", line 115, in train
pred, gold = model(padded_input, input_lengths, padded_target)
File "F:\python\lib\site-packages\torch\nn\modules\module.py", line 541, in call
result = self.forward(*input, **kwargs)
File "G:\github\Speech-Transformer-master\Speech-Transformer-master\transformer\transformer.py", line 35, in forward
input_lengths)
File "F:\python\lib\site-packages\torch\nn\modules\module.py", line 541, in call
result = self.forward(*input, **kwargs)
File "G:\github\Speech-Transformer-master\Speech-Transformer-master\transformer\decoder.py", line 106, in forward
dec_output = self.dropout(self.tgt_word_emb(ys_in_pad) * self.x_logit_scale +
File "F:\python\lib\site-packages\torch\nn\modules\module.py", line 541, in call
result = self.forward(*input, **kwargs)
File "F:\python\lib\site-packages\torch\nn\modules\sparse.py", line 114, in forward
self.norm_type, self.scale_grad_by_freq, self.sparse)
File "F:\python\lib\site-packages\torch\nn\functional.py", line 1484, in embedding
return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.cuda.IntTensor instead (while checking arguments for embedding)
thanks again

**Comment by foamliu** [comment]
No, you cannot.

**Comment by ArtemisZGL** [comment]
i modify the code mostly the pad_list function in  transformer/utils to achieve that, but the gpu usage is not very high, it seems that should change the dataloader which is on the fly to extract feature, making the cpu op become the bottleneck.
