### ISSUE TITLE
Encountered some problems during training

### ISSUE THREAD

**Issue by deep-darkfantasy** [foamliu/Speech-Transformer#6]
Traceback (most recent call last):
  File "G:/github/Speech-Transformer-master/Speech-Transformer-master/train.py", line 170, in <module>
    main()
  File "G:/github/Speech-Transformer-master/Speech-Transformer-master/train.py", line 166, in main
    train_net(args)
  File "G:/github/Speech-Transformer-master/Speech-Transformer-master/train.py", line 73, in train_net
    logger=logger)
  File "G:/github/Speech-Transformer-master/Speech-Transformer-master/train.py", line 115, in train
    pred, gold = model(padded_input, input_lengths, padded_target)
  File "F:\python\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "G:\github\Speech-Transformer-master\Speech-Transformer-master\transformer\transformer.py", line 35, in forward
    input_lengths)
  File "F:\python\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "G:\github\Speech-Transformer-master\Speech-Transformer-master\transformer\decoder.py", line 106, in forward
    dec_output = self.dropout(self.tgt_word_emb(ys_in_pad) * self.x_logit_scale +
  File "F:\python\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "F:\python\lib\site-packages\torch\nn\modules\sparse.py", line 114, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "F:\python\lib\site-packages\torch\nn\functional.py", line 1484, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.cuda.IntTensor instead (while checking arguments for embedding)

Can someone tell me why? Thank you
python 3.66
tensorflow-gpu         1.14.0
torch                  1.3.1+cu92

**Comment by foamliu** [comment]
Have not met such errors. I'm afraid you've to troubleshoot yourself.
