### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'bool'

### ISSUE THREAD

**Issue by w5688414** [foamliu/Speech-Transformer#8]
error occurs:
`
Traceback (most recent call last):
  File "train.py", line 170, in <module>
    main()
  File "train.py", line 166, in main
    train_net(args)
  File "train.py", line 73, in train_net
    logger=logger)
  File "train.py", line 115, in train
    pred, gold = model(padded_input, input_lengths, padded_target)
  File "/home/wugaosheng/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wugaosheng/Speech-Transformer/transformer/transformer.py", line 32, in forward
    encoder_padded_outputs, *_ = self.encoder(padded_input, input_lengths)
  File "/home/wugaosheng/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wugaosheng/Speech-Transformer/transformer/encoder.py", line 60, in forward
    slf_attn_mask=slf_attn_mask)
  File "/home/wugaosheng/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wugaosheng/Speech-Transformer/transformer/encoder.py", line 84, in forward
    enc_input, enc_input, enc_input, mask=slf_attn_mask)
  File "/home/wugaosheng/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wugaosheng/Speech-Transformer/transformer/attention.py", line 52, in forward
    output, attn = self.attention(q, k, v, mask=mask)
  File "/home/wugaosheng/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wugaosheng/Speech-Transformer/transformer/attention.py", line 77, in forward
    attn = attn.masked_fill(mask.bool(), -np.inf)
AttributeError: 'Tensor' object has no attribute 'bool'
`
my torch version is torch (1.4.0)

**Comment by foamliu** [comment]
The code is tested in PyTorch 1.3.0, could you have a try?
